#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc config border_radius       5
bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config active_border_color '#2E3440'
bspc config normal_border_color '#2E3440'
bspc config focused_border_color '#81A1C1'
bspc config presel_feedback_color "#81A1C1"

bspc monitor HDMI1 -d 1 2 3 4
bspc monitor HDMI2 -d 5 6 7 8

# Autostart

dunst --config "${HOME}/.config/dunst/dunstrc" &

picom --experimental-backends --config $HOME/.config/picom/picom.conf &

#[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &
[ -n "$(pidof polkit-gnome)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

sh $HOME/.screenlayout/triple.sh &
#sh $HOME/.screenlayout/double.sh &

sh $HOME/.local/bin/gofaster &

xfce4-power-manager &

[ -n "$(pidof mpd)" ] || mpd &
#[ ! -s ~/.config/mpd/pid ] && mpd &

#nitrogen --restore &
feh --bg-scale $HOME/Pictures/New\ Wallpapers/polyblue.jpg &

sh $HOME/.config/polybar/bspwm/launch.sh &

xsetroot -cursor_name left_ptr 
