#!/bin/sh

## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Parse colors from "~/.Xresources"
xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    #FOREGROUND="$(xrdb_query '*.foreground:')"
    BACKGROUND="$(xrdb_query '*.background:')"
    BLACK="$(xrdb_query '*.color0:')"
    #RED="$(xrdb_query '*.color1:')"
    #GREEN="$(xrdb_query '*.color2:')"
    #YELLOW="$(xrdb_query '*.color3:')"
    #BLUE="$(xrdb_query '*.color4:')"
    #MAGENTA="$(xrdb_query '*.color5:')"
    #CYAN="$(xrdb_query '*.color6:')"
    #WHITE="$(xrdb_query '*.color7:')"
}

getcolors

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run EWW.
$HOME/.local/bin/eww daemon &
sh $HOME/.config/eww/dashboard/scripts/weather_info --getdata &
sh $HOME/.config/eww/sidebar/scripts/getWeather &

# Run notification daemon.
dunst --config "${HOME}/.config/dunst/dunstrc" &

# Run Picom.
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

# Run polkit daemon if doesn't started.
#[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &
[ -n "$(pidof polkit-gnome)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#sh $HOME/.screenlayout/triple.sh &
sh $HOME/.screenlayout/double.sh R

sh $HOME/.local/bin/gofaster &

# Run power manager.
xfce4-power-manager &

# Run mpd if doesn't started.
#[ -n "$(pidof mpd)" ] || mpd &
[ ! -s ~/.config/mpd/pid ] && mpd &

# Execute bspwm-specific scripts.
bspfloat &

# Start X wallpaper.
nitrogen --restore &

# Start polybar
sh $HOME/.config/polybar/bspwm/launch.sh &

# Fix cursor.
xsetroot -cursor_name left_ptr 

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# Triple Monitors
#bspc monitor HDMI1 -d I IV VII
#bspc monitor HDMI2 -d II V VIII
#bspc monitor VGA1 -d III VI IX

# Dual Display
#bspc monitor HDMI1 -d I III V VII IX
#bspc monitor HDMI2 -d II IV VI VIII X

# Dual Display
bspc monitor HDMI1 -d I II III IV
bspc monitor HDMI2 -d V VI VII VIII

rule -a xfce4-terminal              follow=on focus=on
rule -a Code                        follow=on focus=on
rule -a brave                       follow=on focus=on
rule mpv                            state=floating
rule sxiv                           state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config top_padding 36
config border_width 2
config window_gap 10
config split_ratio 0.52

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

config normal_border_color "#2E3440"
config focused_border_color "#5E81AC"
config presel_feedback_color "$#88C0D0"

# Double Border
#pkill 2bspwm ; 2bspwm &
#bash /home/josh/.config/bspwm/bspwm_colors.sh &
