#! /bin/sh

# Autostart
sxhkd &
~/.screenlayout/bspwm.sh &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
mpd &
~/.config/polybar/Theme31/launch.sh &
~/.local/bin/gofaster &
~/.config/bspwm/borders &

# Monitor Setup
bspc monitor HDMI-1 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII IX X

# Settings
bspc config border_width          2
bspc config window_gap            12
bspc config normal_border_color   "#7c7c74"
bspc config active_border_color   "#7c7c74"
bspc config focused_border_color  "#82d4f8"
bspc config presel_feedback_color "#f2e097"

#bspc config automatic_scheme      spiral
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config border_radius         6

# Application Rules
#bspc rule -a Brave-browser desktop='^1'
bash /home/josh/.config/bspwm/bspwm_colors.sh &
